MD004:
  style: dash
MD013:
  enabled: false
MD024:
  siblings_only: true
MD029:
  style: ordered
MD049:
  style: underscore
MD050:
  style: asterisk
MD033:
  allowed_elements:
    - time
    - kbd
    - br
    - samp
    - sup
    - small
    - q
