// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = 'Michaël’s coding thoughts';
export const SITE_DESCRIPTION = 'I&#039;m a software developer for Info Support in the Netherlands. I try to blog my experiences on Microsoft technologies I encounter while working on a variety of projects. My specialties are SharePoint, Project Server, LINQ, WCF, Pex, SQL Server, sharing knowledge and presenting.';
export const PAGE_SIZE = 5;

// Plugins
export const ACRONYMS = {
    'AD': 'Active Directory',
    'AI': 'Artificial Intelligence',
    'API': 'Application Programming Interface',
    'ARM': 'Azure Resource Manager',
    'ASP': 'Active Server Pages',
    'CD': 'Continuous Deployment',
    'CI': 'Continuous Integration',
    'CLI': 'Command Line Interface',
    'CMS': 'Content Management System',
    'CPU': 'Central Processing Unit',
    'CRLF': 'Carriage Return Line Feed',
    'CRM': 'Customer Relationship Management',
    'CSV': 'Comma-separated Values',
    'DLL': 'Dynamic Link Library',
    'DNS': 'Domain Name System',
    'DTO': 'Data Transfer Object',
    'Dapr': 'Distributed Application Runtime',
    'GAC': 'Global Assembly Cache',
    'HD': 'High-definition',
    'HTML': 'HyperText Markup Language',
    'HTTP': 'HyperText Transfer Protocol',
    'IIS': 'Internet Information Services',
    'IMAP': 'Internet Message Access Protocol',
    'IP': 'Internet Protocol',
    'ISO': 'International Organization for Standardization',
    'IaC': 'Infrastructure as Code',
    'JSON': 'JavaScript Object Notation',
    'LF': 'Line Feed',
    'LIS': 'Linux Integration Services',
    'MCSA': 'Microsoft Certified Solutions Associate',
    'MCSD': 'Microsoft Certified Solutions Developer',
    'MSDN': 'Microsoft Developer Network',
    'MSI': 'Microsoft Installer',
    'MVC': 'Model-View-Controller',
    'MVP': 'Most Valuable Professional',
    'MX': 'Mail Exchanger',
    'NDA': 'Non-Disclosure Agreement',
    'NTP': 'Network Time Protocol',
    'ONNX': 'Open Neural Network Exchange',
    'PHP': 'PHP: Hypertext Preprocessor (recursive acronym)',
    'POCO': 'Plain Old CLR Object',
    'PSI': 'Project Server Interface',
    'Perl': 'Practical Extraction and Reporting Language',
    'REST': 'Representational State Transfer',
    'RGB': 'Red, Green, and Blue',
    'SDK': 'Software Development Kit',
    'SLA': 'Service Level Agreement',
    'SMSS': 'SQL Server Management Studio',
    'SMTP': 'Simple Mail Transfer Protocol',
    'SP1': 'Service Pack 1',
    'SP2': 'Service Pack 2',
    'SQL': 'Structured Query Language',
    'SSP': 'Shared Service Provider',
    'STSADM': 'SharePoint Team Services Administration',
    'TCP': 'Transmission Control Protocol',
    'TFS': 'Team Foundation Server',
    'TSQL': 'Transact-SQL',
    'UI': 'User Interface',
    'URI': 'Uniform Resource Identifier',
    'URL': 'Uniform Resource Locator',
    'UTF': 'Unicode Transformation Format',
    'UWP': 'Universal Windows Platform',
    'UX': 'User Experience',
    'VM': 'Virtual Machine',
    'VSTS': 'Visual Studio Team Services',
    'WP': 'WordPress',
    'WSS': 'Windows SharePoint Services',
    'XML': 'eXtensible Markup Language',
};
